#!/usr/bin/env python
#coding:utf-8

"""
Django settings for djproject project.

Generated by 'django-admin startproject' using Django 1.10rc1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

ADMINS=(
        ("zero","575784862@qq.com")
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%+4q%nz!6@kff$09-3#@#b22-a!ldep94*-ugdy@b)b#b0*-_9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG=False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #管理工具类
    'django.contrib.auth',  #管理类Users和Groups
    'django.contrib.contenttypes', #管理工具
    'django.contrib.sessions', #sessions管理工具
    'django.contrib.messages', #消息管理工具
    'django.contrib.staticfiles', #管理静态文件(css,js等)
    'jobs',
    'books',
    'templatebase',
    'djproject',
]

#配置中间件(中间件的作用范围是在view处理request或者responese之前，添加的顺序很重要)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #修改admin页面语言为本地语言
    'django.middleware.common.CommonMiddleware', #通用中间件，开启连接中断警报功能
    'django.middleware.csrf.CsrfViewMiddleware', #防止csrf攻击的管理类
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #replace('\\','/')实现将windows路径翻译为linux路径格式
        'DIRS': [
            (os.path.join(BASE_DIR, 'books')).replace('\\','/'),
            (os.path.join(BASE_DIR, 'jobs')).replace('\\','/'),
            (os.path.join(BASE_DIR, 'djproject')).replace('\\','/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'books.context_processors.custom_proc',
            ],
        },
    },
]

WSGI_APPLICATION = 'djproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #设置为mysql数据库
        'NAME': 'django',  #mysql数据库名
        'USER': 'root',  #mysql用户名，留空则默认为当前linux用户名
        'PASSWORD': '123456',   #mysql密码
        'HOST': '',  #留空默认为localhost
        'PORT': '',  #留空默认为3306端口
    }
}

#缓存设置
#使用分布式缓存(需要安装memcached)
#CACHE_BACKEND="memcached://172.19.26.240:11211;172.19.26.242:11212;172.19.26.244:11213/'"
#使用数据库缓存
CACHE_BACKEND="db://test_cachetable/?timeout=60&max_entries=5" #timeout指定缓存的生存周期，max_entries指定缓存的最大条数
#使用本地文件系统缓存
#CACHE_BACKEND="file///var/tmp"
#使用本地内存缓存
#CACHE_BACKEND="locmem:///"

#email相关配置
EMAIL_USE_SSL=True
EMAIL_HOST="smtp.qq.com"
EMAIL_PORT="465"
EMAIL_HOST_USER="575784862@qq.com"
EMAIL_HOST_PASSWORD="zero199248"


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

#自定义多个静态文件目录(对应不同应用)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
